# roster.R -- The frozen release roster and its accessor.
#
# The roster is the fifteen released members (nine core, six supporting)
# ratified in the necessity register. Regenerated by hand from
# versions_release_freeze_2026-09-02.csv in the ORCHESTRA leader workspace;
# the freeze date is carried as an attribute on the internal data.frame, not
# a column, so it reads once and cannot drift row by row. Re-run the freeze
# and edit this file when the leader workspace re-freezes the roster.

# ---- The frozen roster -----------------------------------------------------
.orchestra_roster <- data.frame(
  member = c(
    "flexyBayes", "PESTO", "kernR", "apsimR", "quorum",
    "terroir", "masque", "decideR", "grainPlan",
    "gpfield", "kalmix", "koine", "proxymix", "optimix", "cdzoo"
  ),
  version = c(
    "0.10.0", "0.10.1", "0.8.2", "0.3.0", "0.1.0",
    "0.2.0", "0.11.0", "0.1.0", "0.1.1",
    "0.3.0", "0.5.0", "0.3.0", "0.15.2", "0.1.0", "0.2.0"
  ),
  tier = c(
    "core", "core", "core", "core", "core",
    "core", "core", "core", "core",
    "supporting", "supporting", "supporting", "supporting", "supporting",
    "supporting"
  ),
  role = c(
    "the inference hub",
    "simulator inversion + ensemble UQ",
    "the TACI engine (flagship)",
    "the mechanism member",
    "the consensus layer",
    "the grounded covariate source",
    "the sovereignty bridge",
    "the decision closer",
    "the practitioner last mile",
    "change-of-support spatial GP",
    "state-space + ACI",
    "the fourth opinion",
    "the mixture calculus",
    "the optimisation meta-layer",
    "the causal-discovery harness"
  ),
  visibility = c(
    "private", "public", "public", "private", "private",
    "private", "public", "public", "public",
    "public", "private", "private", "public", "private", "private"
  ),
  repo = paste0(
    "max578/",
    c(
      "flexyBayes", "PESTO", "kernR", "apsimR", "quorum",
      "terroir", "masque", "decideR", "grainPlan",
      "gpfield", "kalmix", "koine", "proxymix", "optimix", "cdzoo"
    )
  ),
  stringsAsFactors = FALSE
)
attr(.orchestra_roster, "freeze_date") <- "2026-09-02"

#' The frozen Crop Analytics Orchestra roster
#'
#' @description
#' Returns the fifteen members released at the 2026-09-02 freeze: nine core
#' and six supporting, each carrying its necessity-register role, the
#' `max578` repository it publishes (or will publish) through, and whether
#' that repository is public yet.
#'
#' @details
#' The roster is fixed data, not a live query -- it answers "what did the
#' release ratify", not "what is installed right now" (that is
#' [cao_versions()]). A member's absence from this data.frame means it is
#' not in the v1.0 release; the necessity register at
#' `release/necessity_register.md` in the ORCHESTRA leader workspace records
#' why each row is here and what was held for v1.1.
#'
#' @returns A data.frame of 15 rows with columns `member` (character),
#'   `version` (character, the frozen version string), `tier` (character,
#'   one of `"core"` or `"supporting"`), `role` (character, a one-line
#'   necessity-register description), `visibility` (character, one of
#'   `"public"` or `"private"` at the freeze date), and `repo` (character,
#'   the `max578` namespace path). The freeze date is carried as the
#'   `"freeze_date"` attribute on the returned object.
#'
#' @seealso [cao_versions()], [cao_status()]
#' @family roster
#' @author Max Moldovan, \email{max.moldovan@@adelaide.edu.au}
#'
#' @examplesIf interactive()
#' cao_roster()
#'
#' @export
cao_roster <- function() {
  return(.orchestra_roster)
}
