on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      # members whose repositories are private cannot be installed here
      _R_CHECK_FORCE_SUGGESTS_: false
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          extra-packages: |
            any::rcmdcheck
            any::testthat
            any::knitr
            any::rmarkdown
            any::ggplot2
            max578/decideR
            max578/gpfield
            max578/grainPlan
            max578/kalmix
            max578/kernR
            max578/masque
            max578/orchestraManifest
            max578/PESTO
            max578/proxymix
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
